### PR TITLE
Updates scmp to version 2.0.0

### LINKED ISSUE #392: scmp 0.0.3 deprecated
SCMP is out of date and should be updated to take advantage of better crypto standard functions.

**Version:** 3.23.1

### Code Snippet
```node
function validateBody(body, expectedValue) {
  var hash = crypto
    .createHash('sha256')
    .update(Buffer.from(body, 'utf-8'))
    .digest('base64');

  return scmp(expectedValue, hash);
}
```

### Exception/Log
```
npm WARN deprecated scmp@0.0.3: scmp v2 uses improved core crypto comparison since Node v6.6.0
```

### Steps to Reproduce
1. Install `twilio` via `npm`

### PR DESCRIPTION
**Pull request by philnash**
Fixes #392

### CODE REVIEW

**Comment by dkundel** [comment]
Hey @philnash! The CI is failing because the `package-lock.json` and the `package.json` are not in sync. I think we should ultimately get rid of it anyways since it doesn't matter for the purpose of a library. But for now can you update it so that the CI runs?

**Comment by csantanapr** [comment]
As a library provider do not include `package-lock.json`

**Comment by kamronbatman** [comment]
While I agree the file should be removed, that is for a different PR.

**Comment by csantanapr** [comment]
How can we move this PR forward and merge? or do we need a new PR?

**Comment by csantanapr** [comment]
Can someone merge this? @philnash @dkundel @kamronbatman

**Comment by kamronbatman** [comment]
@csantanapr, I don't have permission, sorry.

**Comment by csantanapr** [comment]
Who has permission on this repo that can merge it?

**Comment by csantanapr** [comment]
Is this repo abandoned ? No one is going to merge this?

**Comment by csantanapr** [comment]
Thank you @cjcodes

**Pull request merged**
