### PR TITLE
Support surrogate characters in xml builder, e.g. emoji’s

### PR DESCRIPTION
**Pull request by shawandrew**
Attempting to send emoji characters from inside a twiml message e.g. `twiml.message('😀');` will fail in the xml builder code due to a validation check against surrogate characters.  In order to make these supported we can edit the `MessagingResponse.js` to create the builder with support for these characters.

### CODE REVIEW

**Comment by efossier** [comment]
@shawandrew Thanks for the PR, looks good to me.

Can you please add a test which encodes the emoji in `spec/unit/twiml/MessagingResponse.spec.js`? I would do it myself but I cannot push to your fork. Once you do that I'll be happy to merge.

**Comment by jingming** [comment]
@shawandrew If possible, do you mind adding this to `VoiceResponse` as well? If not, just the test should be fine and we will take care of rest!

**Comment by shawandrew** [comment]
Updated with the test for the message response.  Sorry, I've not had experience of the voice response class yet so I'll leave that to you guys.

**Comment by dbachko** [comment]
@shawandrew `allowSurrogateChars` option was removed in a current version of `xmlbuilder`. Now it is following XML 1.1 spec for valid chars instead of 1.0 which supports unicode chars.

**Comment by shawandrew** [comment]
Great thanks!

**Pull request closed without merging**
