### PR TITLE
fix: Add method overload to VoiceResponse.prototype.play

### PR DESCRIPTION
**Pull request by DCtheTall**
# Fixes [#538](https://github.com/twilio/twilio-node/issues/538).

This allows users to use a string as the first argument with TypeScript enabled.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the master branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by DCtheTall** [comment]
I did not check the "added tests" box because this change only affects a type declaration file. If there is a way to add test coverage to this change, I am happy to add it to this PR 😄

**Comment by childish-sambino** [comment]
For a test, you can add a line like this to _examples/typescript/example.ts_: `twiml.play('https://demo.twilio.com/docs/classic.mp3');`

That file gets compiled as part of the unit tests.

**Comment by DCtheTall** [comment]
@childish-sambino Done.

**Comment by childish-sambino** [comment]
FYI, I've updated the generator to apply this change universally: https://github.com/twilio/twilio-node/pull/545

**Pull request merged**
