### PR TITLE
empty body isn't an error condition :S - fixes #63

### LINKED ISSUE #63: Media "delete" returns no error, but data has ``status: 500``.
I'm running this:

    var twilioClient = require("twilio")(<AccountSID>, <AuthToken>);
    twilioClient.messages(<MessageID>).media(<MediaID>).delete(function(err, data) {
          console.log(err, data); // Logs "null, {status: 500, message: 'Empty body'}"
    });

Within the callback, ``err`` is null, but data is ``{status: 500, message: "Empty body"}``.  The media file is successfully deleted.  It's confusing to get a reported 500 status when the command succeeds and no ``err`` is given.

### PR DESCRIPTION
**Pull request by kwhinnery**
Remove incorrect error data from the data object. Returning an empty body is not an error condition.

### CODE REVIEW

**Comment by skimbrel** [comment]
regression test?

**Comment by kwhinnery** [comment]
Still needs one - fixing current tests.

**Comment by kwhinnery** [comment]
@skimbrel should be gtg - if you want to sanity check it right quick that would be great.

**Comment by skimbrel** [comment]
+1

**Pull request merged**
