### PR TITLE
chore: removed unnecessary badge and added relevant badges

### PR DESCRIPTION
**Pull request by tiwarishubham635**
# Fixes #

Removed nodeio.co, twilioquest badges and added relevant badges for download counts and npm version

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-node/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by tiwarishubham635** [comment]
Hey @bnb! The seems to be working when I am looking at it. Maybe try clearing cache or opening from incognito browser?

**Comment by tiwarishubham635** [comment]
But yeah there is some issue with this badge, since I am also seeing a 500 instead of version v4.20.1
Screenshot 2024-01-23 at 10 09 11 AM

**Comment by tiwarishubham635** [comment]
Okay so I investigated over this. The image being rendered is being fetched from some third party API like badgen for npm version. The delay in response from there might cause the image to not render properly. However, the test badge is being used by a Github API only, so that should not break. However, I did saw that breaking as well at times. What is your suggestion? Should we look for other API or remove these badges?

**Comment by tiwarishubham635** [comment]
Okay so I have removed the alt text that appears when badge is broken. So if the badge is broken, it won't show at all!

**Review by kridai — APPROVED** [review]

**Comment by tiwarishubham635** [comment]
Hi @bnb! Please check the changes and if this looks good then we can proceed with this

**Comment by bnb** [comment]
Looks good to me.

**Pull request merged**
