### PR TITLE
Fixed issue in generate.js when trying to attach undefined object.

### PR DESCRIPTION
**Pull request by danielckv**
After a few days of searching, i found finally the issue of this issue: https://github.com/twilio/twilio-node/issues/117

[Review on Reviewable](https://reviewable.io/reviews/twilio/twilio-node/118)

### CODE REVIEW

**Comment by okev** [comment]
Any progress on this? Looks like its still in master and the latest NPM version (2.9.0).

**Comment by Tuetuopay** [comment]
Can someone please put this into the NPM repository ? I have the same issue (though I fixed it locally), but it would be better to have the fix through NPM

**Comment by okev** [comment]
If it helps @Tuetuopay my approach was to fork, fix and npm install from that repo. I've filed a support ticket with Twilio directly, but no response yet.

**Comment by Tuetuopay** [comment]
@okev that's exactly what I ended up doing !

**Comment by carlosdp** [comment]
Thanks!

**Pull request merged**
