### PR TITLE
refactor to expose utility functions to get expected signature/body hash

### LINKED ISSUE #422: expose utility functions to get expected signature/body hash
**Version: 3.28.1**

**Feature request**:

It would be really nice if we could expose some utility functions to get an expected signature/body hash for a given request, replicating the process that happens in the various checks in [`lib/webhooks/webhooks.js`](https://github.com/twilio/twilio-node/blob/master/lib/webhooks/webhooks.js). That way consumers of this sdk can create mock Twilio webhook requests and ensure that their custom implementation is **actually** working (especially for consumers directly calling `validateRequest` and `validateRequestWithBody` in the case of using an http library/framework other than Express).

### PR DESCRIPTION
**Pull request by Charliekenney23**
Closes #422.

### CODE REVIEW

**Comment by Charliekenney23** [comment]
Thanks @childish-sambino. Any thought on when this will make it into an npm release?

**Comment by childish-sambino** [comment]
Tomorrow? Or maybe today. I'll just say soonish. I'll circle back here afterwards.

**Comment by Charliekenney23** [comment]
Awesome, I appreciate it.

**Comment by childish-sambino** [comment]
Permission issues yesterday. They've been resolved so hopefully releasing today.

**Comment by childish-sambino** [comment]
Since we're on the subject, I'm investigating hex-b64 encoding during validation. Have you had to do any workarounds when working with body validation and the `bodySHA256` value?

**Comment by childish-sambino** [comment]
Released as part of 3.29.0

**Comment by Charliekenney23** [comment]
@childish-sambino Sweet, thanks for the update.

**Comment by Charliekenney23** [comment]
@childish-sambino Unrelated to this PR, but do you at Twilio have any thing on the roadmap for creating a Go SDK? I would love to help contribute on getting it up and running as I use Twilio and Go a lot for work (I'm aware of the unofficially supported SDKs, but using a third party for things like webhook request validation scares me).

**Comment by childish-sambino** [comment]
It's not on the roadmap at the moment. I'll bring it up for discussion as I don't know when it was last investigated.

**Comment by Charliekenney23** [comment]
Sweet! Thanks for all the help.

**Comment by childish-sambino** [comment]
Circling back on this, we may look into what the effort is for templating the current libraries which currently have a lot of hand-crafted pieces in our internal code generator. That would make it simpler to support more languages and the current languages. No timeline on when this will happen or when it would be complete.

**Comment by Charliekenney23** [comment]
@childish-sambino Thanks for the update. I'm looking forward to it!

**Pull request merged**
